version: "3.8"

services:
  chatbot:
    build: .
    container_name: chatbot-container
    ports:
      - "8501:8501"
    restart: always
    environment:
      "API_KEY": ""
    volumes:
      - ./data:/app/data

